### ISSUE TITLE
about the weights。。。

### ISSUE THREAD

**Issue by door5719** [kid2013/head_detection#1]
sir , I want to know where the weights and cfg could be downloaded? thank you

**Comment by kid2013** [comment]
hi, you can find the weight file here [Baidu Driver](https://pan.baidu.com/s/10wobhvnuEiBGCTqZmExl_g). code:x6a4
cfg file can be found in the directory ./cfg

**Comment by door5719** [comment]
Thank you

**Comment by Oliverwang** [comment]
Thank you for sharing, the weights link has expired, can you share it?

**Comment by kid2013** [comment]
> Thank you for sharing, the weights link has expired, can you share it?

try again

**Comment by Ye-Xiyong** [comment]
Which cfg file is corresponding to yolov3-crowdhuman_390000.weights？
