### ISSUE TITLE
about the data set

### ISSUE THREAD

**Issue by RenXiandong888** [kid2013/head_detection#2]
Hello, thanks very much for your work.
I try to retrain the model. Can you tell me where to download the head dataset?

**Comment by kid2013** [comment]
hey, the main dataset is [CrowdHuman](http://www.crowdhuman.org)
you may need to handle the dirty labels.
good luck.

**Comment by RenXiandong888** [comment]
Thanks.

**Comment by Oliverwang** [comment]
The weights link has expired. Can you share it again?
